### ISSUE TITLE
Add description, website or topic to the repo

### ISSUE THREAD

**Issue by budhram** [GoLangGirls/golanggirls.github.io#9]
I hardly image any repo with 
- Website
- Description
- Topics

![screenshot from 2018-10-04 00-13-20](https://user-images.githubusercontent.com/1132451/46431853-7b116b00-c76a-11e8-9e1a-4fc1b7ed6794.png)

BTW, Go Girls has been listed now in ETT Website - http://ettindia.com/ -> `Events`

**Comment by smtalimett** [comment]
Shweta status?
